### PR TITLE
make the main function ModularMain()

### PR DESCRIPTION
**Pull request by penguinland**
I don't know how to test this on real hardware, and maybe the right choice is to close this PR without merging. This is really a way to show off how to use `module.ModularMain()` to avoid copying boilerplate to every module we write.

The idea behind the function is that you give it the name of your logger and as many (API, model) pairs as you want, and it stands up the rest of the module for you.

There is no direct benefit to updating all the old modules, but I do think this will make writing new modules faster and easier. (If people copy and paste the old modules as the start of the new ones, maybe they should be updated after all.)

### CODE REVIEW

**Review by thegreatco — APPROVED** [review]
Assuming you have tested this, looks good to me

**Comment by penguinland** [comment]
> Assuming you have tested this

I have not. How do I test modbus stuff? If it's a hassle, let's just close this without merging; it was mostly intended as an example of how to use `ModularMain()` in future modules.

**Comment by penguinland** [comment]
I'm going to close this: I still don't know how to test it out. If you want to convert old modules to use `module.ModularMain()`, you're welcome to do so, but I mainly intended it for new modules created in the future.

**Comment by penguinland** [comment]
Pete clarified: as long as the module still starts up, there's no need to test it further. It does, so I'm going to convert this from a draft PR to a "real" one and merge.

**Pull request merged**
